backend:
  name: github
  repo: Worker1234565/Worker1234565.github.io
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"      

collections:
  - name: "pages"
    label: "Страницы"
    files:
      - label: "Главная"
        name: "home"
        file: "index.html"
        fields:
          - {label: "Заголовок", name: "title", widget: "string"}
          - {label: "Контент", name: "body", widget: "markdown"}
